config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :baskets do
    collection do
      get :paid, :pending
      patch :pay_all
    end
  end


  resources :categories, only: [:index, :show]

  resources :baskets, only: [:show, :index, :update, :destroy]

  resources :nfts do
    resources :baskets, only: [:create, :new]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
  #validates :paid, presence: true
  belongs_to :user
  belongs_to :nft
end

app/models/category.rb
class Category < ApplicationRecord
  validates :category_name, presence: true, inclusion: { in: %w(kitchen bedroom desk arts&crafts ) }
  has_many :nfts

end

app/models/nft.rb
class Nft < ApplicationRecord
  validates :title, :description, :price, presence: true
  has_one_attached :photo
  belongs_to :category
  belongs_to :user
  has_one :basket
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :nfts
  has_one :basket
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  def index
    @baskets = Basket.all
  end

  def paid
    @baskets = Basket.where(paid: true, user_id: current_user)
  end

  def update
    @basket = Basket.find(params[:id])
    @basket.update(paid: true)
    @nft = Nft.find(@basket.nft_id)
    @nft.update(paid: true)
    flash["payment"] = "Payment confirmed"
    redirect_to pending_baskets_path
  end

  def pay_all
    @baskets = Basket.where(paid: false, user_id: current_user)
    @baskets.each do |basket|
      basket.update(paid: true)
      @nft = Nft.find(basket.nft_id)
      @nft.update(paid: true)
    end
    flash["payment"] = "Payment confirmed"
    redirect_to paid_baskets_path
  end

  def pending
    @baskets = Basket.where(paid: false, user_id: current_user)
    @total = 0
    @baskets.each { |basket| @total += basket.nft.price }
  end

  def show
    @basket = Basket.find(params[:id])
  end

  def new
    @basket = Basket.new
    @nft = Nft.find(params[:nft_id])
  end

  def create
    @nft = Nft.find(params[:nft_id])
    @basket = Basket.new(basket_params)
    @basket.nft = @nft
    @basket.user = current_user
    @basket.paid = false
    if @basket.save
      redirect_to pending_baskets_path
    else
      redirect_to nfts_path
    end
  end

  def destroy
    @basket = Basket.find(params[:id])
    @basket.destroy
    redirect_to pending_baskets_path
  end

  private

  def basket_params
    params.require(:basket).permit(:nft_id, :paid)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    if params[:query].present?
      @nfts = @category.nfts.where(title: params[:query])
    else
      @nfts = @category.nfts.where(paid: false)
    end
  end
end

app/controllers/nfts_controller.rb
class NftsController < ApplicationController
  def index
    @nft = Nft.all
  end

  def show
    @nft = Nft.find(params[:id])
    @basket = Basket.new
  end

  def new
    @nft = Nft.new
    @basket = Basket.new
  end

  def create
    @nft = Nft.new(nft_params)
    @nft.user_id = current_user.id
    if @nft.save
      redirect_to nft_path(@nft)
    else
      render :new
    end
  end

  def update
    @nft = Nft.find(params[:id])
    @nft.update(params[:nft])
  end

  def destroy
    @nft = Nft.find(params[:id])
    @nft.destroy
  end


  private

  def nft_params
    params.require(:nft).permit(:title, :description, :price, :category_id, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #skip_before_action :authenticate_user!, only: :index

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/baskets/index.html.erb
<ul>
  <% @baskets.each do |basket| %>
    <li><%= basket %></li>
  <% end %>
</ul>

app/views/baskets/new.html.erb
<%= simple_form_for([@nft, @basket], method: :post, url: nft_baskets_path) do |f| %>
        <%= f.hidden_field :paid, value: true %>
        <%= f.submit %>
<% end %>

app/views/baskets/paid.html.erb
<div class="container nft-list-filtered-by-category">
  <h1>
    <%= "My Collection" %>
  </h1>
  <ul>
    <div class="container nft-product-cards display-grid">
      <% @baskets.each do |basket| %>
        <li>
          <div class="card-product flex-column">
            <%= link_to nft_path(basket.nft) do %>
              <%= cl_image_tag basket.nft.photo.key %>
            <% end %>
            <div class="card-product-infos">
              <h2><%= link_to basket.nft.title, nft_path(basket.nft), id: "title"  %></h2>
              <p id="price">₿ <%= basket.nft.price %></p>
            </div>
          </div>
        </li>
      <% end %>
    </div>
  </ul>
  <h3>
    <%= link_to "Buy more NFTs", categories_path, id: "collection-link-path" %>
  </h3>
</div>

app/views/baskets/pending.html.erb
<div class="container">
  <div class="basket-pending-index d-flex">
    <ul class="basket-pending-index-grid col-7">
      <% @baskets.each do |basket| %>
        <li class="basket-pending-index-grid-nft-card d-flex flex-column justify-content-center">
          <%= link_to basket.nft.title, basket_path(basket), class: "d-flex justify-content-center" %>
          <%= cl_image_tag basket.nft.photo.key %>
          <%= link_to "Buy", basket_path(basket), method: :patch, :class => 'btn-pay-now'%>
          <%= link_to "Remove", basket_path(basket), method: :delete, :class => 'btn-remove'%>
        </li>
      <% end %>
    </ul>
    <div>
      <div class="checkout-card">
        <ul>
            <% @baskets.each do |basket| %>
              <li>
                <div class="item-price">
                  <div><%= basket.nft.title %>:</div>
                  <div>₿ <%=basket.nft.price %></div>
                </div>
              </li>
            <% end %>
            <hr/>
            <li>
              <div class="item-price">
                <div>TOTAL:</div>
                <div>₿ <%= @total %></div>
              </div>
            </li>
            <%= link_to "Buy All", pay_all_baskets_path, method: :patch, :class => 'btn-pay-all'%>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/baskets/show.html.erb
<div class="container list-inline basket-show">
  <div class="basket-nft-show col-6 list-inline-item">
    <div class="basket-nft-show-top">
      <h1><%= @basket.nft.title %></h1>
      <p><%= @basket.nft.description %></p>
      <% if @basket.nft.photo.key != nil %>
        <%= cl_image_tag @basket.nft.photo.key, height: 300, width: 400, crop: :fill %>
      <% else %>
        <%= image_tag "Image_not_available" %>
      <% end %>
    </div>
    <div class="basket-nft-show-bottom list-inline d-flex justify-content-between">
      <p class="list-inline-item">1 item</p>
      <p class="list-inline-item">$<%= @basket.nft.price %></p>
    </div>
  </div>
  <div class="basket-pay col-5 list-inline-item">
    <%= image_tag "Groupbasket-big.svg", alt: "arrow", class:"basket_logo" %>
    <%= form_for(@basket) do |f| %>
      <%= f.hidden_field :paid, value: true %>
      <%= f.submit "Pay now", class: "submit-button" %>
    <% end %>
  </div>
</div>

app/views/categories/index.html.erb
<div class="container_category_index">
  <div class="title-h2">
    <h2 class = "h2-all">Where do you<br/><span class="h2-bottom">wanna<span class="start-h2">start</span> ?</h2> <br></span>
  </div>
<ul>
  <div id="grid_category_index">
    <div id="first-group">
      <div id="item1">
        <li>
          <div class="card-product flex-column">
            <%= link_to category_path(1) do %>
            <img id= "category-card" src="https://res.cloudinary.com/df0rbvi7s/image/upload/v1642257180/development/kitchen_f7tn51.png" alt="test">
            <% end %>
          </div>
        </li>
      </div>
    <div id="item2">
        <li>
         <div class="card-product flex-column">
            <%= link_to category_path(3) do %>
            <img id= "category-card" src="https://res.cloudinary.com/df0rbvi7s/image/upload/v1642257179/development/desk_eqwtlk.png" alt="test" >
            <% end %>
          </div>
        </li>
      </div>
    </div>

        <div id="second-group">


    <div id="item3">
      <li>
        <div class="card-product flex-column">
          <%= link_to category_path(4) do %>
          <img id= "category-card" src="https://res.cloudinary.com/df0rbvi7s/image/upload/v1642257181/development/arts_crafts_fhtcwj.png" alt="test">
          <% end %>
        </div>
      </li>
    </div>

      <div id="item4">
        <li>
          <div class="card-product flex-column">
            <%= link_to category_path(2) do %>
            <img id= "category-card" src="https://res.cloudinary.com/df0rbvi7s/image/upload/v1642257179/development/bedroom_za5hr7.png" alt="test" >
            <% end %>
          </div>
        </li>
      </div>

  </div>
</ul>
</div>

app/views/categories/show.html.erb
<div class="container nft-list-filtered-by-category">
<div class="search-bar-container">
  <h1>
    <%= @category.category_name.capitalize %>
  </h1>
  <div class="searchbar">
<%= form_tag category_path(@category), method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find an NFT"
  %>



<% end %>
</div>
</div>
  <ul>
    <div class="container nft-product-cards display-grid">
      <% @nfts.each do |nft| %>
        <li>
          <div class="card-product flex-column">
            <%= link_to nft_path(nft) do %>
              <%= cl_image_tag nft.photo.key %>
            <% end %>
            <div class="card-product-infos">
              <h2><%= link_to nft.title, nft_path(nft), id: "title" %></h2>
              <p id="price">₿ <%= nft.price %></p>
            </div>
          </div>
        </li>
      <% end %>
    </div>
  </ul>
  <h3>
    <%= link_to "Back to Categories", categories_path, id: "path-to-index" %>
  </h3>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesignAgencyMetaverse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/nfts/index.html.erb
<div class="banner">
  <h1>Make the <span>metaverse</span> your place</h1>
  <%= link_to 'Shop now', '#', class: "button" %>
  <%= image_tag "vector.png", alt: "arrow", width: 40 %>



</div>

<div class="container">

  </div>
</div>

app/views/nfts/new.html.erb
<h1>Add your NFT</h1>

<div class="container-form-new">
  <%= simple_form_for [ @nft ] do |f| %>
    <div class="create-nft-form">
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.association :category, label_method: :category_name %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Create NFT", class: "new-nft-btn" %>
    </div>
  <% end %>
</div>

app/views/nfts/show.html.erb
  <div class="flex-1">
    <div class="box-1">
      <h2 class="h2_nft_show"><%= @nft.title %></h2>
    </div>


    <div class="box-2">
      <%= cl_image_tag @nft.photo.key, crop: :fill, class: "image_nft" %>
    </div>

     <div class="box-3">
      <p class= "price">₿ <%= @nft.price %></p>
    </div>

    </div>


  <div class="flex-2">
  <div class="box-4">
      <br>
        <p class="description" ><%= @nft.description %></p>
      <br>
  </div>



<div class="box-5">

  <div class="basket_buton_flex">

    <%= simple_form_for [@nft, @basket], { html: { class: "form-button-nft-show" } } do |f| %>
            <%= f.hidden_field :paid, value: true %>
            <%= f.submit "Add to my Basket" , class:"basket_button" %>
  </div>

  <div class="logo-bouton_flex">

    <%= image_tag "basket_nft_show.svg", alt: "arrow", width: 40, class:"basket_nft_show" %>
  </div>

  <% end %>
</div>
</div>

app/views/pages/home.html.erb
<div class="banner">
  <div class="test">
    <h1 class="h1-home">Make the<span>metaverse</span>your place.</h1>
  </div>
  <div class="d-flex flex-row-reverse">
    <%= link_to categories_path do %>
    <%= image_tag "button.svg", alt: "arrow", width: 40, class:"button_png" %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>
<% if flash["payment"] %>
    <div class="container col-4 payment-alert" role="alert"><p class="my-3">Payment Confirmed</p></div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar">
    <%= link_to image_tag("https://uxwing.com/wp-content/themes/uxwing/download/10-brands-and-social-media/meta.png", alt: "meta logo", class: "logo-navbar"), root_path, class: "logo" %>
  <ul class="nav-links" id="categories">
    <li class="nav-item-underlined <%= 'active' if @category && @category.id == 1%> "><%= link_to "KITCHEN", category_path(1), class:"nav-link" %></li>
    <li class="nav-item-underlined <%= 'active' if @category && @category.id == 2%>"><%= link_to "BEDROOM", category_path(2), class:"nav-link" %></li>
    <li class="nav-item-underlined <%= 'active' if @category && @category.id == 3%>"><%= link_to "DESK", category_path(3), class:"nav-link" %></li>
    <li class="nav-item-underlined <%= 'active' if @category && @category.id == 4%>"><%= link_to "ARTS&CRAFTS", category_path(4), class:"nav-link" %></li>
  </ul>
  <ul class="nav-links">
      <li class="nav-item"><%= link_to "MY BASKET", pending_baskets_path %></li>
      <li class="nav-item"><%= image_tag "akar-icons_basket.svg", alt: "arrow", class:"basket_logo",width: 40 %></li>
      <li class="nav-item"><%= link_to Basket.where(paid: false, user_id: current_user).count, pending_baskets_path %></li>

    <li class="nav-item-dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My collection", paid_baskets_path, class: "dropdown-item" %>
              <%= link_to "Sell an NFT", new_nft_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
    </li>

  </ul>


</nav>

app/views/shared/_nft-card.html.erb
<div class="card-product">
  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
  <div class="card-product-infos">
    <h2><%= nft.title %></h2>
    <p><%= nft.description %></p>
  </div>
</div>